nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome...')
letras = len(nome)-nome.count(' ')
print('Seu nome em maiúscula é {}'.format(nome.upper()))
print('Seu nome em minúscula é {}'.format(nome.lower()))
print('Seu nome ao todo tem {} letras'.format(letras))
print('Seu primeiro nome tem {}'.format(nome.find(' ')))
separa = nome.split()
print('Seu primeiro nome é {}'.format(separa[0]))
